routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TesController;
use App\Http\Controllers\ProdukController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::prefix('produk')->group(function () {
    Route::get('/datatable',[ProdukController::class, 'datatable'])->name('produk.datatable');
});
Route::prefix('tes')->group(function () {
    Route::get('/',[TesController::class, 'index'])->name('tes.index');
    Route::get('/api',[TesController::class, 'api'])->name('tes.api');
    Route::get('/palindrome',[TesController::class, 'palindrome'])->name('tes.palindrome');
});
Route::resources([
    'produk' => ProdukController::class,
]);

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    use HasFactory;
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produk;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class ProdukController extends Controller
{
    
    public function index()
    {
        return view('produk.index');
    }
    public function datatable(Request $request)
    {
        $a=Produk::selectRaw('produks.*,IF(produks.dijual=1, "Bisa Dijual", "Tidak Bisa Dijual") as status')
        ->where('dijual',1);
        $datatables = DataTables::of($a);
        return $datatables->addColumn('action',function($a){
            $dropdown='<div class="btn-group dropleft">
                <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-h"></i>
                </button>
                <div class="dropdown-menu">
                <a class="dropdown-item edit" href="#" id="'.$a->id.'">Edit</a>
                <a class="dropdown-item hapus" href="#" id="'.$a->id.'">Hapus</a>
                </div>
            </div';
            return $dropdown;
        })->addColumn('harga',function($a){
            return number_format($a->harga,2,',','.');
        })->rawColumns(['action'])->make(true);
    }
    public function store(Request $request)
    {
        $rules=[
            'nama' => 'required',
            'harga' => 'required|numeric',
            'kategori' => 'required',
            'status'=>'required',
        ];
        $request->validate($rules);
        $a=new Produk();
        $a->nama=$request->nama;
        $a->harga=$request->harga;
        $a->kategori=$request->kategori;
        $a->dijual=$request->status;
        if ($a->save()) {
            return response()->json([
                "message"=>"Data berhasil ditambahkan !",
            ], 200);
        }
        return response()->json([
            "message"=>"Data gagal ditambahkan !",
        ], 500);
    }
    public function edit($id)
    {
        $a=Produk::where('id',$id)->firstOrFail();
        return response()->json([
            "data"=>$a,
            "message"=>"",
        ], 200);
    }
    public function update(Request $request, $id)
    {
        $rules=[
            'nama' => 'required',
            'harga' => 'required|numeric',
            'kategori' => 'required',
            'status'=>'required',
        ];
        $request->validate($rules);
        $a=Produk::findOrFail($id);
        $a->nama=$request->nama;
        $a->harga=$request->harga;
        $a->kategori=$request->kategori;
        $a->dijual=$request->status;
        if ($a->update()) {
            return response()->json([
                "message"=>"Data berhasil diubah !",
            ], 200);
        }
        return response()->json([
            "message"=>"Data gagal diubah !",
        ], 500);
    }
    public function destroy($id)
    {
        $a=Produk::findOrFail($id);
        if ($a->delete()) {
            return response()->json([
                "message"=>"Data berhasil dihapus !",
            ], 200);
        }
        return response()->json([
            "message"=>"Data gagal dihapus !",
        ], 500);
    }
}

resources/views/produk/create.blade.php
<div class="modal fade" id="modal-create">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Form Tambah Data</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form action="{{route('produk.store')}}" method="POST" id="form-create">
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="nama">Nama</label>
                            <input type="text" class="form-control" id="nama" name="nama">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="kategori">Kategori</label>
                            <input type="text" class="form-control" id="kategori" name="kategori">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="harga">Harga</label>
                            <input type="text" class="form-control" id="harga" name="harga">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="status">Status</label>
                            <div>
                                <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="status" id="status-1" value="1">
                                <label class="form-check-label" for="status-1">Bisa Dijual</label>
                                </div>
                                <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="status" id="status-2" value="0">
                                <label class="form-check-label" for="status-2">Tidak Bisa Dijual</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {{csrf_field()}}
              
        </div>
        <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
            <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
        </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
    </div>

resources/views/produk/edit.blade.php
<div class="modal fade" id="modal-edit">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Form Edit Data</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form action="" method="POST" id="form-edit">
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="nama-edit">Nama</label>
                            <input type="text" class="form-control" id="nama-edit" name="nama">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="kategori-edit">Kategori</label>
                            <input type="text" class="form-control" id="kategori-edit" name="kategori">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="harga-edit">Harga</label>
                            <input type="text" class="form-control" id="harga-edit" name="harga">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="status-edit">Status</label>
                            <div>
                                <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="status" id="status-1-edit" value="1">
                                <label class="form-check-label" for="status-1-edit">Bisa Dijual</label>
                                </div>
                                <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="status" id="status-2-edit" value="0">
                                <label class="form-check-label" for="status-2-edit">Tidak Bisa Dijual</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {{csrf_field()}}
                {{method_field('PATCH')}}
              
        </div>
        <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
            <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
        </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
    </div>

resources/views/produk/index.blade.php
@extends('layout',['title'=>'Produk'])
@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <button type="button" class="btn btn-primary btn-sm" id="tambah-data"><i class="fas fa-plus"></i> Tambah Data</button>
                        </h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="table-data" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>#ID</th>
                                        <th>Nama</th>
                                        <th>Kategori</th>
                                        <th>Harga</th>
                                        <th>Status</th>
                                        <th>&nbsp;</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
    @include('produk.create')
    @include('produk.edit')
@endsection
@section('script_under')
<script>
$(document).ready(function() {
    var table = $('#table-data').DataTable({
		processing:true,
		serverSide:true,
		ajax:'{{ route('produk.datatable') }}',
		"order": [[ 0, "asc" ]],
		"lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
		columns:[
            {data:'id', name:'id'},
			{data:'nama', name:'nama'},
			{data:'kategori', name:'kategori'},
            {data:'harga', name:'harga'},
			{data:'status', name:'dijual',searchable:false},
			{data:'action',name:'action',orderable:false,searchable:false},
		],
        "columnDefs": [
            {className: "text-center", "targets": [4]}
        ]
	});
    var rulesCreate={
            nama: {
                required: true,
            },
            kategori: {
                required: true,
            },
            harga: {
                required: true,
                number:true,
            },
            status: {
                required: true,
            },
        }
    var formCreate = $( "#form-create" ).validate({
        rules: rulesCreate,
        submitHandler: function (form) {
            $('#modal-create').LoadingOverlay("show");
            $.ajax({
                type: form.method,
                url: form.action,
                data: $(form).serialize(),
                complete: function (data) {
                    $('#modal-create').LoadingOverlay("hide");
                },
                success: function (response) {
                    Swal.fire({
                        icon: 'success',
                        title: response.message,
                        showConfirmButton: true,
                        showCloseButton: true,
                        timer:1500,
                    });
                    $('#modal-create').modal('hide');
                    table.ajax.reload();
                },
                error: function (request, status, error) {
                    Swal.fire({
                        icon: 'error',
                        title: request.responseJSON.message,
                        showConfirmButton: true,
                        showCloseButton: true,
                    });
                }
            });
        }
    });
    $('#tambah-data').click(function (e) { 
        e.preventDefault();
        $("#form-create").find('.is-invalid').removeClass('is-invalid');
        $('#modal-create').modal('show');
        $( "#form-create")[0].reset();
        formCreate.resetForm();
    });
    var rulesEdit={
        nama: {
            required: true,
        },
        kategori: {
            required: true,
        },
        harga: {
            required: true,
            number:true,
        },
        status: {
            required: true,
        },
    }
    var formEdit = $( "#form-edit" ).validate({
        rules: rulesEdit,
        submitHandler: function (form) {
            $('#modal-edit').LoadingOverlay("show");
            $.ajax({
                type: form.method,
                url: form.action,
                data: $(form).serialize(),
                complete: function (data) {
                    $('#modal-edit').LoadingOverlay("hide");
                },
                success: function (response) {
                    Swal.fire({
                        icon: 'success',
                        title: response.message,
                        showConfirmButton: true,
                        showCloseButton: true,
                        timer:1500,
                    });
                    $('#modal-edit').modal('hide');
                    table.ajax.reload();
                },
                error: function (request, status, error) {
                    Swal.fire({
                        icon: 'error',
                        title: request.responseJSON.message,
                        showConfirmButton: true,
                        showCloseButton: true,
                    });
                }
            });
        }
    });
    $("#table-data").on('click','.edit', function (e) {
        e.preventDefault();
        $("#form-edit").find('.is-invalid').removeClass('is-invalid');
        var id = $(this).attr('id');
        var urlUpdate = "{{route('produk.update',['produk'=>':id'])}}";
        $( "#form-edit" ).attr('action',urlUpdate);
        urlUpdate = $( "#form-edit" ).attr('action').replace(':id',id);
        $( "#form-edit" ).attr('action',urlUpdate);
        var urlEdit = "{{route('produk.edit',['produk'=>':id'])}}";
        urlEdit = urlEdit.replace(':id',id);
        $.ajax({
            type: "GET",
            url: urlEdit,
            dataType: "JSON",
            success: function (response) {
                $('#modal-edit').modal('show');
                $( "#form-edit" )[0].reset();
                formEdit.resetForm();
                $('#nama-edit').val(response.data.nama);
                $('#kategori-edit').val(response.data.kategori);
                $('#harga-edit').val(response.data.harga);
                if (response.data.dijual==1) {
                    $('#status-1-edit').attr('checked', 'checked');
                }
                else if(response.data.dijual==0){
                    $('#status-2-edit').attr('checked', 'checked');
                }
            },
            error: function (request, status, error) {
                Swal.fire({
                    icon: 'error',
                    title: request.responseJSON.message,
                    showConfirmButton: true,
                    showCloseButton: true,
                });
            }
        });
    });
    $("#table-data").on('click','.hapus', function (e) {
        e.preventDefault();
        var id = $(this).attr('id');
        var urlDelete = "{{route('produk.destroy',['produk'=>':id'])}}";
        urlDelete = urlDelete.replace(':id',id);
        Swal.fire({
            title: 'Apakah anda yakin?',
            text: "ini adalah hapus permanen!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya, Hapus!'
            }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: "POST",
                    url: urlDelete,
                    data: {_method:'DELETE',_token:'{{csrf_token()}}'},
                    dataType: "JSON",
                    success: function (response) {
                        Swal.fire({
                        icon: 'success',
                        title: response.message,
                        showConfirmButton: true,
                        showCloseButton: true,
                        timer:1500,
                        });
                        table.ajax.reload();
                    },
                    error: function (request, status, error) {
                        Swal.fire({
                        icon: 'error',
                        title: request.responseJSON.message,
                        showConfirmButton: true,
                        showCloseButton: true,
                        });
                    }
                });
            }
        });
    });
});
</script>
@endsection